### ISSUE TITLE
Feature request: sending icon

### ISSUE THREAD

**Issue by ghost** [tylerhall/php-growl#2]
Hi :)

Thanks for this great library.
I'm currently working on integrating this into https://github.com/spotweb/spotweb and everything works fine, except I can't send along a custom icon with my message. Any plan on implementing such a feature?

**Comment by tylerhall** [comment]
Unfortunately, the Growl network protocol doesn't allow for sending an icon. Until they change that, it's not possible.

**Comment by ghost** [comment]
http://growl.info/documentation/developer/introduction.php suggest otherwise.

**Comment by tylerhall** [comment]
You can send a custom icon when connecting to Growl locally, through the Objective-C bindings, but it is not possible when connecting via their network protocol (which is what the PHP script uses).

**Comment by maliayas** [comment]
I think it is about the protocol used. UDP doesnt support callbacks and icons but GTNP does. If you implement GNTP (the original prot. of Growl) callbacks and icons might be possible. There is a similar pear library here: http://growl.laurent-laville.org/
But to me, it is too complicated. It supports both UDP and GNTP btw.
