### ISSUE TITLE
undefined constant

### ISSUE THREAD

**Issue by ghost** [tylerhall/php-growl#5]
Readme says:

```
To configure Growl to use `fsock` instead of `socket` functions you can define a constant:
define('GROWL_SOCK', 'fsock');
```

And yes, that works. But if nothing is defined i get the following warning:

`PHP Notice:  Use of undefined constant GROWL_SOCK - assumed 'GROWL_SOCK' in class.growl.php on line 79`

**Comment by Petah** [comment]
I think this should fix it https://github.com/tylerhall/php-growl/pull/6
