### ISSUE TITLE
Does this still even work?

### ISSUE THREAD

**Issue by DevinClark** [tylerhall/php-growl#9]
I get nothing when I run the example. No errors, no results, nothing... 

Can it be updated or did Apple more or less kill it with Notification Center?

**Comment by tylerhall** [comment]
I don't think it works with Growl 2.0.

**Comment by thenerdnest** [comment]
I've got Growl For Windows v 2.0.9 installed, and I've got a PHP web application successfully sending messages to the client using this class... so yes, definitely still works. However, I've not yet tested with mac.

I did have to add some firewall rules to allow the messages to come inbound. I also added outbound firewall rules on the server side, but I'm not positive whether the server side was necessary or not.
